==== Typed Message Handlers

The logic surrounding the message consumer classes will by default attempt to intelligently convert the body of
the received message from a byte array to a converted type, such as a String. Before routing the message to the
consumer and handler, the plugin will run through a list of <<Message Converters>>, limited by the class types
of the handlers defined in the message consumer, and attempt to find a conversion that works.

For example, consider this JSON blob:

[source,json]
{"foo":"bar","hi":"there"}

If the above message is received, the converter for the Map class type will convert the byte array to a Map
of the JSON data. If a valid handler for the Map type is defined, the handler will receive the converted JSON.

The following handlers would accept the converted map:

[source,groovy]
-----
package com.example

import com.budjb.rabbitmq.consumer.MessageContext

class ExampleConsumer {
    // ...

    def handleMessage(Map body, MessageContext context) {
        // Do work
    }

    def handleMessage(def body, MessageContext context) {
        // Since def is a generic type (Object)
    }
}
-----

If no converter is able to convert the message body, the plugin will fall back to passing the handler the raw
byte array received from the RabbitMQ server.

NOTE: More information about message converters can be found in the <<Message Converters>> section, including a list
of built-in message converters and details of how to create custom converters.
